MEMBERS = [
    {
        "id": 1,
        "name": "Alex Chen",
        "nickname": "The Bibliothecary",
        "tagline": "If it has a map in the front, I'm already reading it.",
        "avatar_seed": "AlexChen",
        "avatar_style": "adventurer",
        "fun_facts": [
            "Has read over 200 fantasy novels",
            "Organizes books by color AND genre simultaneously",
            "Once argued for 45 minutes that The Lord of the Rings is technically one book",
        ],
        "quotes": [
            "World-building is just geography with feelings.",
            "I gave it 5 stars. The ending ruined it. Still 5 stars.",
            "If the author didn't include a glossary, did they even try?",
        ],
        "favorite_genre": "Fantasy / Sci-Fi",
        "rating_style": "Harsh but fair",
        "join_date": "2023-01-15",
        "books_selected": [1, 6],
        "meals_cooked": [1, 9, 17, 23, 27],
        "signature_dish": "Spiced Lamb Kebabs",
        "chef_nickname": "Spice Lord",
    },
    {
        "id": 2,
        "name": "Jamie Rodriguez",
        "nickname": "Plot Twist",
        "tagline": "I cried at the end. No I won't tell you which end.",
        "avatar_seed": "JamieRodriguez",
        "avatar_style": "adventurer",
        "fun_facts": [
            "Always reads the last page first 'just to check'",
            "Has a spreadsheet tracking every book ever read since age 12",
            "Makes desserts so good people forget to discuss the book",
        ],
        "quotes": [
            "The slower the burn, the bigger the fire.",
            "Non-linear narrative is just the author trusting you.",
            "I don't rate books. Books rate me.",
        ],
        "favorite_genre": "Literary Fiction",
        "rating_style": "Emotional and poetic",
        "join_date": "2023-01-15",
        "books_selected": [2],
        "meals_cooked": [5, 12, 18, 22, 28],
        "signature_dish": "Cuban Black Beans & Rice",
        "chef_nickname": "The Dessert Whisperer",
    },
    {
        "id": 3,
        "name": "Sam Kim",
        "nickname": "The Annotator",
        "tagline": "My copy has more highlights than text at this point.",
        "avatar_seed": "SamKim",
        "avatar_style": "adventurer",
        "fun_facts": [
            "Brings printed discussion questions every single meeting",
            "Has never returned a library book late — ever",
            "Once read the same book three times to 'fully appreciate the structure'",
        ],
        "quotes": [
            "The footnotes are half the book. Read the footnotes.",
            "A good author plants seeds 200 pages early.",
            "Subtext is just text for people paying attention.",
        ],
        "favorite_genre": "Non-Fiction / Sci-Fi",
        "rating_style": "Analytical and precise",
        "join_date": "2023-02-01",
        "books_selected": [3],
        "meals_cooked": [8, 14, 20, 25, 30],
        "signature_dish": "Korean-Japanese Fusion Bibimbap",
        "chef_nickname": "The Recipe Annotator",
    },
    {
        "id": 4,
        "name": "Morgan Williams",
        "nickname": "The Contrarian",
        "tagline": "Goodreads gave it 4 stars, which means I give it 2.",
        "avatar_seed": "MorganWilliams",
        "avatar_style": "adventurer",
        "fun_facts": [
            "Proud of having the most 'controversial' takes in the group",
            "Secretly agrees with the group rating 60% of the time",
            "Will defend any unpopular book choice with the tenacity of a defense attorney",
        ],
        "quotes": [
            "Popular doesn't mean good. It just means popular.",
            "The hype was the real villain.",
            "I liked it before it was assigned reading.",
        ],
        "favorite_genre": "Everything the group hasn't read yet",
        "rating_style": "Contrarian but secretly sentimental",
        "join_date": "2023-01-15",
        "books_selected": [4, 7],
        "meals_cooked": [4, 13, 19, 21, 29, 31],
        "signature_dish": "Mole Negro with Duck",
        "chef_nickname": "The Dark Horse Chef",
    },
    {
        "id": 5,
        "name": "Riley Thompson",
        "nickname": "Dramaturgy",
        "tagline": "Every story is a play. I'm just watching for the blocking.",
        "avatar_seed": "RileyThompson",
        "avatar_style": "adventurer",
        "fun_facts": [
            "Former theater kid who now channels it into book discussions",
            "Assigns 'character roles' to everyone in the group",
            "Has an opinion on every cover design",
        ],
        "quotes": [
            "The reveal only works if you earned it.",
            "Setting is character.",
            "I don't care what happened. I care why it matters.",
        ],
        "favorite_genre": "Thriller / Literary Fiction",
        "rating_style": "Dramatic and theatrical",
        "join_date": "2023-03-01",
        "books_selected": [5],
        "meals_cooked": [6, 11, 15, 24, 26, 32],
        "signature_dish": "Stone Fruit & Almond Tart",
        "chef_nickname": "The Stage Manager of Flavor",
    },
]

BOOKS = [
    {
        "id": 1,
        "title": "Dune",
        "author": "Frank Herbert",
        "genre": "Sci-Fi",
        "pages": 896,
        "goodreads_rating": 4.25,
        "year_published": 1965,
        "date_read": "2023-03-15",
        "selected_by": 1,
        "description": "A sweeping tale of desert planets, political intrigue, and ecological mysticism. The book that defined modern science fiction and inspired everything from Star Wars to Avatar.",
        "cover_color": "#c97b2e",
        "cover_accent": "#f5deb3",
        "tags": ["classic", "world-building", "epic", "politics"],
        "ratings": {
            1: {"score": 5.0, "review": "A masterpiece. Every sci-fi trope traces back here. Read it."},
            2: {"score": 3.5, "review": "Great world, glacial pace. Worth it for the lore, but I needed coffee."},
            3: {"score": 4.5, "review": "The political intrigue alone earns a 4.5. Ecological systems thinking ahead of its time."},
            4: {"score": 4.0, "review": "Overrated but in the best possible way. Classic for a reason."},
            5: {"score": 3.0, "review": "Started it three times before I finished it. Beautiful once it clicked."},
        },
    },
    {
        "id": 2,
        "title": "The Seven Husbands of Evelyn Hugo",
        "author": "Taylor Jenkins Reid",
        "genre": "Literary Fiction",
        "pages": 400,
        "goodreads_rating": 4.40,
        "year_published": 2017,
        "date_read": "2023-05-20",
        "selected_by": 2,
        "description": "A reclusive Hollywood icon finally tells her story to an unknown journalist. A dazzling, addictive saga of ambition, identity, and love across a glittering life of secrets.",
        "cover_color": "#8b0000",
        "cover_accent": "#ffd700",
        "tags": ["romance", "Hollywood", "LGBTQ+", "secrets"],
        "ratings": {
            1: {"score": 3.5, "review": "Entertaining but I saw every twist coming. Good beach read though."},
            2: {"score": 5.0, "review": "A perfect novel. I sobbed. I gasped. I called my mother."},
            3: {"score": 4.0, "review": "Structure was immaculate. Could have used 20% more ambiguity."},
            4: {"score": 4.5, "review": "This is what I mean when I say popular can also be good."},
            5: {"score": 4.5, "review": "The theatrical quality of her life! Evelyn Hugo is a legend."},
        },
    },
    {
        "id": 3,
        "title": "Project Hail Mary",
        "author": "Andy Weir",
        "genre": "Sci-Fi",
        "pages": 476,
        "goodreads_rating": 4.52,
        "year_published": 2021,
        "date_read": "2023-07-08",
        "selected_by": 3,
        "description": "A lone astronaut wakes up with no memory on a desperate mission to save Earth. Funny, heartfelt, and stuffed with real science. The most joyful book about humanity's extinction you'll ever read.",
        "cover_color": "#1a237e",
        "cover_accent": "#80deea",
        "tags": ["space", "science", "humor", "survival", "friendship"],
        "ratings": {
            1: {"score": 5.0, "review": "Rocky. That's all. Rocky made me feel things I didn't expect from a physics textbook."},
            2: {"score": 4.0, "review": "The science stuff went over my head but the heart of it was undeniable."},
            3: {"score": 5.0, "review": "Weir made me care about astrophage. ASTROPHAGE. 5 stars."},
            4: {"score": 3.5, "review": "Fun, breezy. A little too neat for my taste. The friendship was sweet."},
            5: {"score": 4.5, "review": "I laughed out loud. In a book about the apocalypse. Remarkable."},
        },
    },
    {
        "id": 4,
        "title": "Piranesi",
        "author": "Susanna Clarke",
        "genre": "Fantasy",
        "pages": 272,
        "goodreads_rating": 4.22,
        "year_published": 2020,
        "date_read": "2023-09-14",
        "selected_by": 4,
        "description": "A man lives in a labyrinthine House whose halls contain infinite statues and oceans. He knows almost nothing, including who he really is. A novel of extraordinary strangeness and quiet devastation.",
        "cover_color": "#3e2723",
        "cover_accent": "#bcaaa4",
        "tags": ["mystery", "fantasy", "surreal", "short", "haunting"],
        "ratings": {
            1: {"score": 4.5, "review": "The most unique reading experience in years. Clarke is operating on another level."},
            2: {"score": 4.0, "review": "I didn't fully understand it but I felt it in my chest. That counts."},
            3: {"score": 3.5, "review": "Beautifully written but I wanted more resolution. Too dreamlike for me."},
            4: {"score": 5.0, "review": "My pick. My masterpiece. The House is real and it has tides."},
            5: {"score": 4.0, "review": "Short, strange, and unforgettable. I thought about it for a week."},
        },
    },
    {
        "id": 5,
        "title": "Tomorrow, and Tomorrow, and Tomorrow",
        "author": "Gabrielle Zevin",
        "genre": "Literary Fiction",
        "pages": 480,
        "goodreads_rating": 4.22,
        "year_published": 2022,
        "date_read": "2023-11-02",
        "selected_by": 5,
        "description": "Two friends build video games together across decades. A novel about creativity, love, loss, and what it means to make something that outlasts you. Also the best book about friendship written in years.",
        "cover_color": "#1b5e20",
        "cover_accent": "#a5d6a7",
        "tags": ["gaming", "friendship", "creativity", "decades-spanning"],
        "ratings": {
            1: {"score": 4.0, "review": "The gaming details were perfect. The emotional core even more so."},
            2: {"score": 5.0, "review": "I wept at the end. Beautiful meditation on creative partnership."},
            3: {"score": 4.5, "review": "The game development accuracy alone earns extra points. Rare authenticity."},
            4: {"score": 3.0, "review": "Good but I found Sam frustrating in all the wrong ways."},
            5: {"score": 5.0, "review": "My pick. Vindicated. This is the novel of our generation."},
        },
    },
    {
        "id": 6,
        "title": "The Midnight Library",
        "author": "Matt Haig",
        "genre": "Fiction",
        "pages": 304,
        "goodreads_rating": 3.98,
        "year_published": 2020,
        "date_read": "2024-01-18",
        "selected_by": 1,
        "description": "Between life and death lies a library containing every version of your life you could have lived. Nora Seed has the chance to undo her regrets. But which life is the right one?",
        "cover_color": "#1a237e",
        "cover_accent": "#7986cb",
        "tags": ["mental health", "philosophy", "hope", "parallel lives"],
        "ratings": {
            1: {"score": 4.5, "review": "Cozy philosophy wrapped in a warm blanket. I needed this one."},
            2: {"score": 4.5, "review": "The message hit me exactly when I needed it to."},
            3: {"score": 3.5, "review": "The concept was stronger than the execution. But I smiled at the end."},
            4: {"score": 2.5, "review": "Inspiring premise. Very predictable arc. I've seen this movie."},
            5: {"score": 4.0, "review": "Accessible and warm. The Haig earnestness lands more often than not."},
        },
    },
    {
        "id": 7,
        "title": "Mexican Gothic",
        "author": "Silvia Moreno-Garcia",
        "genre": "Gothic Horror",
        "pages": 320,
        "goodreads_rating": 3.85,
        "year_published": 2020,
        "date_read": "2024-03-07",
        "selected_by": 4,
        "description": "1950s Mexico. A glamorous socialite investigates her cousin's mysterious illness at a remote mansion run by a deeply unsettling English family. Gothic horror with a feminist, colonial critique at its heart.",
        "cover_color": "#4a148c",
        "cover_accent": "#ce93d8",
        "tags": ["horror", "gothic", "Mexico", "feminism", "colonialism"],
        "ratings": {
            1: {"score": 4.5, "review": "The atmosphere alone is worth five stars. Deeply unsettling in the best way."},
            2: {"score": 4.0, "review": "Noemi is a fantastic protagonist. The ending got weird but I was along for the ride."},
            3: {"score": 3.5, "review": "Elegant prose but the horror mechanics felt a bit genre-by-numbers to me."},
            4: {"score": 4.5, "review": "My second pick. Still great. The colonial horror is not subtle and shouldn't be."},
            5: {"score": 5.0, "review": "The creep factor built perfectly. That house is evil and I loved every page."},
        },
    },
]

MEALS = [
    # Book 1: Dune — Desert/Arabian Nights theme
    {
        "id": 1,
        "book_id": 1,
        "dish": "Spiced Lamb Kebabs with Harissa",
        "prepared_by": 1,
        "description": "Tender chunks of lamb marinated overnight in a blend of cumin, coriander, smoked paprika, and preserved lemon, skewered and charred. Served with house harissa and warm flatbread.",
        "type": "Main",
        "recipe": {
            "ingredients": [
                "2 lbs lamb shoulder, cut into chunks",
                "3 tbsp harissa paste",
                "2 tsp cumin",
                "1 tsp smoked paprika",
                "1 tsp coriander",
                "Juice of 1 preserved lemon",
                "4 garlic cloves, minced",
                "2 tbsp olive oil",
                "Salt and pepper",
                "Fresh mint for serving",
            ],
            "steps": [
                "Combine all marinade ingredients in a bowl. Add lamb and coat thoroughly.",
                "Marinate overnight in the fridge (minimum 4 hours).",
                "Thread lamb onto metal skewers.",
                "Grill on high heat 4-5 minutes per side until charred and cooked through.",
                "Rest 5 minutes. Serve with extra harissa and fresh mint on warm flatbread.",
            ],
        },
    },
    {
        "id": 2,
        "book_id": 1,
        "dish": "Saffron & Cardamom Basmati",
        "prepared_by": 2,
        "description": "Long-grain basmati rice bloomed with saffron and cardamom, finished with toasted pine nuts and golden raisins. Fragrant enough to make you feel the spice must flow.",
        "type": "Side",
        "recipe": {
            "ingredients": [
                "2 cups basmati rice, rinsed",
                "Large pinch of saffron threads",
                "3 cardamom pods, cracked",
                "1/4 cup pine nuts, toasted",
                "1/4 cup golden raisins",
                "2 tbsp butter",
                "4 cups chicken or vegetable stock",
                "Salt",
            ],
            "steps": [
                "Bloom saffron in 2 tbsp warm water for 10 minutes.",
                "In a heavy pot, melt butter over medium heat. Toast cardamom pods 1 minute.",
                "Add rice and stir to coat in butter, 2 minutes.",
                "Add stock and saffron water. Bring to boil, then reduce to lowest heat.",
                "Cover and cook 15 minutes. Rest 5 minutes off heat.",
                "Fluff with fork. Fold in pine nuts and raisins.",
            ],
        },
    },
    {
        "id": 3,
        "book_id": 1,
        "dish": "Date & Walnut Baklava",
        "prepared_by": 3,
        "description": "Crispy phyllo layered with a filling of dates, walnuts, and rose water syrup. Sticky, sweet, and dangerously easy to eat. The spice of dessert.",
        "type": "Dessert",
        "recipe": None,
    },
    {
        "id": 4,
        "book_id": 1,
        "dish": "Moroccan Mint Tea Service",
        "prepared_by": 4,
        "description": "Traditional Moroccan mint tea poured from height to create a frothy top. Served with sugar cubes and dried apricots. The Water of Life in liquid form.",
        "type": "Drink",
        "recipe": {
            "ingredients": [
                "2 tbsp Chinese gunpowder green tea",
                "Large bunch fresh spearmint",
                "4-6 sugar cubes (or to taste)",
                "4 cups boiling water",
            ],
            "steps": [
                "Rinse the teapot with a splash of boiling water, then discard.",
                "Add green tea to pot and pour in 1 cup boiling water. Swirl briefly and pour this water out (this removes bitterness).",
                "Add mint and sugar to pot. Fill with remaining 3 cups boiling water.",
                "Steep 3-4 minutes.",
                "Pour tea into a glass from high up to create froth, then pour back into pot. Repeat twice.",
                "Serve in small glasses, pouring from height.",
            ],
        },
    },
    # Book 2: Evelyn Hugo — Cuban / Hollywood Glamour theme
    {
        "id": 5,
        "book_id": 2,
        "dish": "Arroz con Frijoles Negros",
        "prepared_by": 2,
        "description": "The real Cuban black beans and rice — slow-cooked sofrito base, black beans with bay leaves and cumin, served alongside fluffy white rice. Evelyn would approve.",
        "type": "Main",
        "recipe": {
            "ingredients": [
                "1 lb dried black beans, soaked overnight",
                "1 large onion, finely diced",
                "1 green bell pepper, finely diced",
                "6 garlic cloves, minced",
                "1 tsp cumin",
                "1 tsp oregano",
                "2 bay leaves",
                "2 tbsp olive oil",
                "Salt, pepper",
                "2 cups white rice, cooked",
                "Fresh cilantro to serve",
            ],
            "steps": [
                "Drain soaked beans. Cover with fresh water by 2 inches and bring to boil.",
                "Simmer 1-1.5 hours until beans are tender. Reserve cooking liquid.",
                "In a skillet, make sofrito: cook onion and pepper in olive oil until soft, 10 min.",
                "Add garlic, cumin, oregano. Cook 2 minutes more.",
                "Mash a spoonful of beans into the sofrito to thicken.",
                "Combine sofrito with beans. Add bay leaves and some bean liquid.",
                "Simmer 20 minutes until thick and creamy. Season to taste.",
                "Serve over white rice with fresh cilantro.",
            ],
        },
    },
    {
        "id": 6,
        "book_id": 2,
        "dish": "Maduros (Fried Sweet Plantains)",
        "prepared_by": 5,
        "description": "Ripe plantains, caramelized in a hot pan until deeply golden and almost jammy. Simple, perfect, unforgettable. The supporting character that steals every scene.",
        "type": "Side",
        "recipe": {
            "ingredients": [
                "3 very ripe plantains (black-yellow skin)",
                "Vegetable oil for frying",
                "Pinch of salt",
            ],
            "steps": [
                "Peel plantains and slice diagonally into 1/2-inch pieces.",
                "Heat 1/4 inch of oil in a skillet over medium-high heat.",
                "Fry plantain slices 2-3 minutes per side until golden-caramel colored.",
                "Remove to a paper towel-lined plate. Sprinkle with a pinch of salt.",
                "Serve immediately while warm.",
            ],
        },
    },
    {
        "id": 7,
        "book_id": 2,
        "dish": "Mojito Cheesecake",
        "prepared_by": 4,
        "description": "A no-bake cheesecake with rum, fresh lime, and mint layered into every component — from the Graham cracker base to the mint-lime curd on top. Glamorous and dangerous.",
        "type": "Dessert",
        "recipe": None,
    },
    {
        "id": 8,
        "book_id": 2,
        "dish": "Old Fashioned Cocktail Bar",
        "prepared_by": 3,
        "description": "A proper build-your-own Old Fashioned station. Rye whiskey, bourbon, aromatic bitters, Demerara sugar, orange peel. The cocktail Evelyn Hugo would have nursed through every difficult conversation.",
        "type": "Drink",
        "recipe": {
            "ingredients": [
                "2 oz rye whiskey or bourbon",
                "1 tsp Demerara sugar syrup (or 1 sugar cube)",
                "2-3 dashes Angostura bitters",
                "1 large ice cube",
                "Orange peel for garnish",
                "Luxardo cherry (optional)",
            ],
            "steps": [
                "Place sugar and bitters in a rocks glass. Muddle briefly to combine.",
                "Add a large ice cube.",
                "Pour whiskey over ice.",
                "Stir gently for 20-30 seconds to chill and slightly dilute.",
                "Express orange peel over the glass, rub around rim, and drop in.",
                "Add cherry if using. Sip slowly.",
            ],
        },
    },
    # Book 3: Project Hail Mary — Space / Science theme
    {
        "id": 9,
        "book_id": 3,
        "dish": "Rocky's World Beet & Goat Cheese Salad",
        "prepared_by": 1,
        "description": "Roasted golden and red beets arranged to look like Ryland and Rocky's two very different home planets. Goat cheese, candied walnuts, arugula, and a balsamic glaze. Technically accurate.",
        "type": "Starter",
        "recipe": {
            "ingredients": [
                "3 medium red beets",
                "3 medium golden beets",
                "4 oz goat cheese, crumbled",
                "1/2 cup candied walnuts",
                "4 cups arugula",
                "3 tbsp balsamic glaze",
                "2 tbsp olive oil",
                "Salt and pepper",
            ],
            "steps": [
                "Roast beets: wrap individually in foil with a drizzle of olive oil. Roast at 400°F for 45-60 minutes until tender.",
                "Let cool, then peel and slice into rounds.",
                "Arrange arugula on a large platter.",
                "Fan out red and golden beet slices, alternating (the two planets).",
                "Scatter goat cheese and walnuts over top.",
                "Drizzle with olive oil and balsamic glaze.",
                "Season with salt and pepper. Serve immediately.",
            ],
        },
    },
    {
        "id": 10,
        "book_id": 3,
        "dish": "Astrophage Spicy Tacos",
        "prepared_by": 1,
        "description": "Named for the solar parasite that started it all. Smoked chipotle chicken with a bright mango habanero salsa that burns just like an astrophage converting mass to energy.",
        "type": "Main",
        "recipe": None,
    },
    {
        "id": 11,
        "book_id": 3,
        "dish": "Stranded Astronaut Ice Cream Sundaes",
        "prepared_by": 5,
        "description": "A build-your-own sundae bar featuring freeze-dried strawberries, actual astronaut ice cream crumbled on top, and a hot fudge 'solar flare' swirl. Science approved.",
        "type": "Dessert",
        "recipe": None,
    },
    {
        "id": 12,
        "book_id": 3,
        "dish": "Fancy Astronaut Snack Mix",
        "prepared_by": 2,
        "description": "A gourmet trail mix of freeze-dried fruits, dark chocolate chips, toasted coconut, smoked almonds, and sea salt. What the Hail Mary crew would have eaten if catering was involved.",
        "type": "Snack",
        "recipe": {
            "ingredients": [
                "1 cup smoked almonds",
                "1/2 cup freeze-dried mango",
                "1/2 cup freeze-dried raspberries",
                "1/2 cup dark chocolate chips (70%)",
                "1/4 cup toasted coconut flakes",
                "1/4 cup pepitas",
                "Flaky sea salt",
            ],
            "steps": [
                "Combine all ingredients in a large bowl.",
                "Toss gently to distribute.",
                "Spread on a sheet tray and sprinkle flaky sea salt over the top.",
                "Portion into small cups or bags for serving.",
            ],
        },
    },
    # Book 4: Piranesi — Ancient / Mysterious / Labyrinthine theme
    {
        "id": 13,
        "book_id": 4,
        "dish": "Marble Cake with Lavender Frosting",
        "prepared_by": 4,
        "description": "A swirled vanilla-chocolate marble cake to honor the House's infinite marble halls. Frosted with a pale lavender buttercream that smells like something between a memory and a dream.",
        "type": "Dessert",
        "recipe": None,
    },
    {
        "id": 14,
        "book_id": 4,
        "dish": "Ancient Grain Tabbouleh",
        "prepared_by": 3,
        "description": "Farro, freekeh, and bulgur wheat tossed with mountains of fresh parsley, tomato, cucumber, mint, lemon, and olive oil. Grains from civilizations that understood the labyrinth.",
        "type": "Side",
        "recipe": {
            "ingredients": [
                "1/2 cup farro, cooked and cooled",
                "1/2 cup bulgur wheat, cooked and cooled",
                "2 cups flat-leaf parsley, finely chopped",
                "1/2 cup fresh mint, chopped",
                "2 tomatoes, deseeded and diced",
                "1 cucumber, diced",
                "Juice of 2 lemons",
                "3 tbsp olive oil",
                "Salt and pepper",
            ],
            "steps": [
                "Combine cooled farro and bulgur in a large bowl.",
                "Add parsley, mint, tomato, and cucumber.",
                "Dress with lemon juice and olive oil.",
                "Season generously with salt and pepper.",
                "Taste and adjust lemon — it should be bright and assertive.",
                "Let sit 15 minutes before serving for flavors to meld.",
            ],
        },
    },
    {
        "id": 15,
        "book_id": 4,
        "dish": "Stone Fruit & Almond Tart",
        "prepared_by": 5,
        "description": "A buttery tart shell filled with frangipane and topped with sliced plums, cherries, and apricots arranged in concentric rings. As precise and beautiful as the Hall of the Third Vestibule.",
        "type": "Dessert",
        "recipe": None,
    },
    {
        "id": 16,
        "book_id": 4,
        "dish": "Honey Mead",
        "prepared_by": 3,
        "description": "A homemade quick mead — honey, water, and a touch of yeast — given a week to ferment gently. Ancient, sweet, faintly effervescent. The drink of the statues.",
        "type": "Drink",
        "recipe": None,
    },
    # Book 5: Tomorrow, and Tomorrow, and Tomorrow — Nostalgic / Gaming theme
    {
        "id": 17,
        "book_id": 5,
        "dish": "Vintage Retro Charcuterie Board",
        "prepared_by": 5,
        "description": "A sprawling board styled after the 80s and 90s gaming era: Velveeta alongside aged cheddar, Ritz crackers next to artisan sourdough, luncheon meat roses beside proper prosciutto. Nostalgic and ironic.",
        "type": "Starter",
        "recipe": None,
    },
    {
        "id": 18,
        "book_id": 5,
        "dish": "Korean-Japanese Fusion Bibimbap",
        "prepared_by": 3,
        "description": "A full bibimbap spread — seasoned spinach, bean sprouts, julienned carrots, shiitake mushrooms, bulgogi beef, and a fried egg over stone-pot rice — nodding to Sam's Korean heritage in the novel.",
        "type": "Main",
        "recipe": {
            "ingredients": [
                "4 cups cooked short-grain rice",
                "200g beef sirloin, thinly sliced",
                "2 tbsp soy sauce, 1 tbsp sesame oil, 1 tbsp sugar (for beef marinade)",
                "200g spinach, blanched and squeezed dry",
                "200g bean sprouts, blanched",
                "2 carrots, julienned",
                "200g shiitake mushrooms, sliced",
                "4 eggs",
                "4 tbsp gochujang (Korean chili paste)",
                "2 tbsp sesame seeds",
                "Sesame oil for drizzling",
            ],
            "steps": [
                "Marinate beef in soy, sesame oil, sugar for 30 min. Pan-fry until caramelized.",
                "Season spinach with soy sauce and sesame oil.",
                "Sauté carrots and mushrooms separately, each with a little sesame oil and salt.",
                "Season bean sprouts with soy, sesame oil, and a pinch of sugar.",
                "Fry eggs sunny-side up.",
                "Serve rice in individual bowls. Arrange toppings in sections around the bowl.",
                "Top with fried egg. Add gochujang and sesame seeds. Drizzle with sesame oil.",
                "Mix vigorously before eating.",
            ],
        },
    },
    {
        "id": 19,
        "book_id": 5,
        "dish": "Pixel Art Rice Crispy Treats",
        "prepared_by": 2,
        "description": "Classic rice crispy treats decorated with colored icing to look like 8-bit video game sprites. Took two hours to make and three minutes to eat. Worth every second.",
        "type": "Dessert",
        "recipe": None,
    },
    {
        "id": 20,
        "book_id": 5,
        "dish": "Classic Strawberry Shortcake",
        "prepared_by": 1,
        "description": "From-scratch shortcake biscuits, macerated fresh strawberries, and barely-sweetened whipped cream. A Sadie specialty — simple, perfect, timeless.",
        "type": "Dessert",
        "recipe": {
            "ingredients": [
                "2 cups flour",
                "2 tbsp sugar",
                "1 tbsp baking powder",
                "1/2 tsp salt",
                "1/2 cup cold butter, cubed",
                "3/4 cup heavy cream, plus more for brushing",
                "1 lb fresh strawberries, hulled and sliced",
                "2 tbsp sugar (for strawberries)",
                "1 cup heavy whipping cream",
                "1 tbsp powdered sugar",
            ],
            "steps": [
                "Toss strawberries with 2 tbsp sugar. Let macerate 30 minutes.",
                "For shortcakes: whisk flour, sugar, baking powder, salt.",
                "Cut in cold butter until mixture looks like coarse crumbs.",
                "Add cream and stir just until dough comes together.",
                "Pat out to 3/4-inch thick and cut into rounds.",
                "Brush tops with cream. Bake at 425°F for 12-14 minutes until golden.",
                "Whip cream with powdered sugar to soft peaks.",
                "Split shortcakes, fill with strawberries and whipped cream.",
            ],
        },
    },
    # Book 6: The Midnight Library — Cozy Comfort Food theme
    {
        "id": 21,
        "book_id": 6,
        "dish": "Mulligatawny Soup",
        "prepared_by": 4,
        "description": "A rich, spiced British-Indian soup with chicken, lentils, apple, and coconut cream. The most comforting thing imaginable — exactly what you'd want between lives.",
        "type": "Main",
        "recipe": {
            "ingredients": [
                "2 chicken breasts, cooked and shredded",
                "1 cup red lentils",
                "1 onion, diced",
                "2 carrots, diced",
                "1 Granny Smith apple, peeled and diced",
                "3 garlic cloves",
                "1 tbsp curry powder",
                "1 tsp cumin",
                "1/2 tsp turmeric",
                "400ml coconut cream",
                "1 liter chicken stock",
                "2 tbsp butter",
                "Juice of 1 lime",
                "Fresh cilantro to serve",
            ],
            "steps": [
                "Melt butter in a large pot. Sauté onion and carrot until soft, 8 minutes.",
                "Add garlic, curry powder, cumin, turmeric. Cook 2 minutes until fragrant.",
                "Add apple, lentils, and chicken stock. Bring to boil.",
                "Simmer 20 minutes until lentils are completely soft.",
                "Stir in coconut cream and shredded chicken. Heat through.",
                "Season with lime juice and salt.",
                "Serve with a swirl of coconut cream and fresh cilantro.",
            ],
        },
    },
    {
        "id": 22,
        "book_id": 6,
        "dish": "'Every Possibility' Tapas Spread",
        "prepared_by": 2,
        "description": "Fourteen small dishes representing fourteen possible lives: patatas bravas, gambas al ajillo, Manchego with quince, pan con tomate, and more. Every bite a different version of the same meal.",
        "type": "Starter",
        "recipe": None,
    },
    {
        "id": 23,
        "book_id": 6,
        "dish": "Matcha Everything Platter",
        "prepared_by": 1,
        "description": "Matcha mochi, matcha cookies, matcha latte, matcha chocolate bark. A meditation on a single ingredient across infinite forms. Morgan's thesis: even a limited palette has infinite combinations.",
        "type": "Dessert",
        "recipe": None,
    },
    {
        "id": 24,
        "book_id": 6,
        "dish": "Earl Grey Lavender Shortbread",
        "prepared_by": 5,
        "description": "Buttery Scottish shortbread infused with loose-leaf Earl Grey and dried lavender. The kind of biscuit that belongs in a library between lifetimes.",
        "type": "Dessert",
        "recipe": {
            "ingredients": [
                "225g unsalted butter, softened",
                "100g powdered sugar",
                "2 tbsp loose Earl Grey tea (leaves removed from bags)",
                "1 tsp dried culinary lavender, chopped",
                "280g plain flour",
                "Pinch of salt",
                "Turbinado sugar for rolling",
            ],
            "steps": [
                "Beat butter and powdered sugar until pale and fluffy.",
                "Stir in Earl Grey leaves and lavender.",
                "Fold in flour and salt until a soft dough forms.",
                "Shape into a log, roll in turbinado sugar, wrap in cling film.",
                "Chill at least 1 hour (or overnight).",
                "Slice into 1/2-inch rounds. Place on lined baking tray.",
                "Bake at 325°F for 14-16 minutes until pale golden at edges.",
                "Cool completely before eating — they firm up as they cool.",
            ],
        },
    },
    # Book 7: Mexican Gothic — Gothic / Day of the Dead theme
    {
        "id": 25,
        "book_id": 7,
        "dish": "Mole Negro with Duck Legs",
        "prepared_by": 4,
        "description": "A proper mole negro — 30 ingredients including three types of chili, charred vegetables, dark chocolate, and a secret. Slow-braised duck legs drowning in it. Took two days to make.",
        "type": "Main",
        "recipe": None,
    },
    {
        "id": 26,
        "book_id": 7,
        "dish": "Chiles en Nogada",
        "prepared_by": 5,
        "description": "Poblano peppers stuffed with a sweet-savory picadillo of pork, raisins, and spices, blanketed in a walnut cream sauce and scattered with pomegranate seeds. Mexico's most dramatic dish.",
        "type": "Main",
        "recipe": None,
    },
    {
        "id": 27,
        "book_id": 7,
        "dish": "Pan de Muerto",
        "prepared_by": 1,
        "description": "Traditional Day of the Dead sweet bread, soft and pillowy with orange zest and anise, decorated with bone-shaped dough and a sugar skull on top. Baked with love and mild existential dread.",
        "type": "Bread",
        "recipe": {
            "ingredients": [
                "4 cups flour",
                "1/2 cup sugar",
                "1 packet active dry yeast",
                "1/2 cup warm milk",
                "1/2 cup butter, melted",
                "4 eggs",
                "Zest of 1 orange",
                "1 tsp anise seeds",
                "1 tsp salt",
                "1/4 cup butter + 1/4 cup sugar for topping",
            ],
            "steps": [
                "Dissolve yeast in warm milk with a pinch of sugar. Let sit 10 minutes until foamy.",
                "Mix flour, sugar, salt, anise. Add yeast mixture, eggs, butter, and orange zest.",
                "Knead 10 minutes until smooth and elastic. Dough will be slightly sticky.",
                "Let rise in oiled bowl, covered, 1-2 hours until doubled.",
                "Punch down. Shape into a round loaf. Reserve some dough for decorations.",
                "Roll thin ropes and cross them over the top. Add a small ball at center.",
                "Let rise 45 more minutes. Bake at 350°F for 25-30 minutes until golden.",
                "While warm, brush with melted butter and roll in sugar.",
            ],
        },
    },
    {
        "id": 28,
        "book_id": 7,
        "dish": "Mezcal Negroni with Black Salt",
        "prepared_by": 2,
        "description": "A smoky mezcal negroni — mezcal instead of gin, Campari, sweet vermouth — served in a coupe rimmed with volcanic black salt. Tastes like something the Doyles would have served at a very bad dinner party.",
        "type": "Drink",
        "recipe": {
            "ingredients": [
                "1.5 oz mezcal (joven or reposado)",
                "1 oz Campari",
                "1 oz sweet vermouth",
                "Black lava salt for rim",
                "Orange twist to garnish",
                "Large ice cube",
            ],
            "steps": [
                "Rim a coupe or rocks glass with a citrus wedge, then dip in black salt.",
                "Fill a mixing glass with ice. Add mezcal, Campari, and sweet vermouth.",
                "Stir 30 seconds until well-chilled.",
                "Strain into your prepared glass over a large ice cube.",
                "Express orange twist over the glass and use as garnish.",
                "Sip and contemplate the horror.",
            ],
        },
    },
]
