"""
One-time migration: copies data/bookclub.db (SQLite) into Supabase Postgres,
and uploads static/avatars/* into the Supabase "avatars" storage bucket.

Requires env vars: DATABASE_URL, SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY
(same ones app.py needs — see README for where to find them in Supabase).

Run ONCE, after the Supabase project + "avatars" bucket exist:
    python migrate_to_supabase.py
"""

import mimetypes
import os
import sqlite3
import sys

import psycopg2
import requests
from psycopg2.extras import RealDictCursor

BASE          = os.path.dirname(__file__)
SQLITE_PATH   = os.path.join(BASE, "data", "bookclub.db")
AVATARS_DIR   = os.path.join(BASE, "static", "avatars")

DATABASE_URL              = os.environ["DATABASE_URL"]
SUPABASE_URL              = os.environ["SUPABASE_URL"]
SUPABASE_SERVICE_ROLE_KEY = os.environ["SUPABASE_SERVICE_ROLE_KEY"]
AVATAR_BUCKET              = "avatars"

SCHEMA = """
CREATE TABLE IF NOT EXISTS members (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT NOT NULL,
    nickname       TEXT    DEFAULT '',
    avatar_seed    TEXT    DEFAULT '',
    avatar_img     TEXT,
    fun_facts      TEXT    DEFAULT '[]',
    quotes         TEXT    DEFAULT '[]',
    favorite_genre TEXT    DEFAULT '',
    join_date      TEXT    DEFAULT '',
    signature_dish TEXT    DEFAULT ''
);

CREATE TABLE IF NOT EXISTS books (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            TEXT NOT NULL,
    author           TEXT    DEFAULT '',
    genre            TEXT    DEFAULT '',
    pages            INTEGER DEFAULT 0,
    goodreads_rating REAL    DEFAULT 0,
    year_published   INTEGER DEFAULT 0,
    date_read        TEXT    DEFAULT '',
    selected_by      INTEGER REFERENCES members(id) ON DELETE SET NULL,
    description      TEXT    DEFAULT '',
    cover_color      TEXT    DEFAULT '#444444',
    cover_accent     TEXT    DEFAULT '#888888',
    tags             TEXT    DEFAULT '[]',
    event_note       TEXT    DEFAULT '',
    goodreads_url    TEXT    DEFAULT '',
    cover_img        TEXT    DEFAULT ''
);

CREATE TABLE IF NOT EXISTS ratings (
    book_id   INTEGER NOT NULL REFERENCES books(id)   ON DELETE CASCADE,
    member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
    score     REAL    NOT NULL,
    review    TEXT    DEFAULT '',
    PRIMARY KEY (book_id, member_id)
);

CREATE TABLE IF NOT EXISTS meals (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id     INTEGER REFERENCES books(id)   ON DELETE CASCADE,
    dish        TEXT NOT NULL,
    prepared_by INTEGER REFERENCES members(id) ON DELETE SET NULL,
    type        TEXT DEFAULT '',
    description TEXT DEFAULT '',
    recipe      TEXT
);
"""

TABLES = {
    "members": ["id", "name", "nickname", "avatar_seed", "avatar_img", "fun_facts",
                "quotes", "favorite_genre", "join_date", "signature_dish"],
    "books":   ["id", "title", "author", "genre", "pages", "goodreads_rating",
                "year_published", "date_read", "selected_by", "description",
                "cover_color", "cover_accent", "tags", "event_note",
                "goodreads_url", "cover_img"],
    "meals":   ["id", "book_id", "dish", "prepared_by", "type", "description", "recipe"],
}


def copy_table(sqlite_db, pg_cur, table, columns):
    rows = sqlite_db.execute(f"SELECT * FROM {table}").fetchall()
    cols_sql = ", ".join(columns)
    placeholders = ", ".join(f"%({c})s" for c in columns)
    for row in rows:
        pg_cur.execute(
            f"INSERT INTO {table} ({cols_sql}) VALUES ({placeholders})",
            {c: row[c] for c in columns},
        )
    if rows:
        pg_cur.execute(
            f"SELECT setval(pg_get_serial_sequence(%s, 'id'), (SELECT MAX(id) FROM {table}))",
            (table,),
        )
    print(f"  Copied {len(rows)} rows into {table}")


def copy_ratings(sqlite_db, pg_cur):
    rows = sqlite_db.execute("SELECT * FROM ratings").fetchall()
    for row in rows:
        pg_cur.execute(
            "INSERT INTO ratings (book_id, member_id, score, review) VALUES (%s, %s, %s, %s)",
            (row["book_id"], row["member_id"], row["score"], row["review"]),
        )
    print(f"  Copied {len(rows)} rows into ratings")


def upload_avatars():
    if not os.path.isdir(AVATARS_DIR):
        print("  No static/avatars directory found — skipping avatar upload")
        return
    files = [f for f in os.listdir(AVATARS_DIR) if os.path.isfile(os.path.join(AVATARS_DIR, f))]
    for filename in files:
        content_type = mimetypes.guess_type(filename)[0] or "application/octet-stream"
        with open(os.path.join(AVATARS_DIR, filename), "rb") as f:
            resp = requests.put(
                f"{SUPABASE_URL}/storage/v1/object/{AVATAR_BUCKET}/{filename}",
                data=f.read(),
                headers={
                    "Authorization": f"Bearer {SUPABASE_SERVICE_ROLE_KEY}",
                    "apikey": SUPABASE_SERVICE_ROLE_KEY,
                    "Content-Type": content_type,
                    "x-upsert": "true",
                },
            )
            resp.raise_for_status()
    print(f"  Uploaded {len(files)} avatar files to the '{AVATAR_BUCKET}' bucket")


def run():
    if not os.path.exists(SQLITE_PATH):
        print(f"No SQLite database found at {SQLITE_PATH} — nothing to migrate.")
        sys.exit(1)

    sqlite_db = sqlite3.connect(SQLITE_PATH)
    sqlite_db.row_factory = sqlite3.Row

    pg = psycopg2.connect(DATABASE_URL, cursor_factory=RealDictCursor)
    pg_cur = pg.cursor()

    pg_cur.execute("SELECT COUNT(*) AS n FROM information_schema.tables WHERE table_name='books'")
    if pg_cur.fetchone()["n"]:
        pg_cur.execute("SELECT COUNT(*) AS n FROM books")
        existing = pg_cur.fetchone()["n"]
        if existing:
            answer = input(
                f"Supabase 'books' table already has {existing} row(s). "
                "Re-running will likely duplicate data or fail on id conflicts.\n"
                "Continue anyway? [y/N] "
            )
            if answer.strip().lower() != "y":
                print("Aborted — nothing changed.")
                return

    print("Creating schema (if not already present)...")
    pg_cur.execute(SCHEMA)
    pg.commit()

    print("Copying data...")
    copy_table(sqlite_db, pg_cur, "members", TABLES["members"])
    copy_table(sqlite_db, pg_cur, "books", TABLES["books"])
    copy_ratings(sqlite_db, pg_cur)
    copy_table(sqlite_db, pg_cur, "meals", TABLES["meals"])
    pg.commit()

    print("Uploading avatars to Supabase Storage...")
    upload_avatars()

    pg.close()
    sqlite_db.close()
    print("\nDone. Data is now live in Supabase.")


if __name__ == "__main__":
    run()
